

logging:
  level:
    org.springframework.data.r2dbc: DEBUG

spring:
  codec.max-in-memory-size: 512MB
  r2dbc:
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:
  datasource:
    driver-class-name: org.h2.Driver
